"""Export product_master, indexed by company_id, to web/v3/v3-products.js.

Used by the v3 dashboard's interactive globe — when the user clicks a company
dot on a country mini-map, the detail card needs to render the company's actual
products (name / brand / commercial path / technology / material) instead of
just a count.

This produces a single JS file (~200-400 KB) that registers
window.V3_PRODUCTS_BY_COMPANY = { 'co_xxx': [ {name, brand, l1, l2, tech, ...}, ... ] }
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "global_aesthetics.db"
OUT = ROOT / "web" / "v3" / "v3-products.js"

QUERY = """
SELECT
  company_id,
  product_id,
  standard_product_name,
  registered_name,
  brand,
  brand_role,
  commercial_path_l1,
  commercial_path_l2,
  technology_path_l1,
  technology_path_l2,
  material_or_energy_source,
  core_product,
  verified_differentiator,
  feature_tags
FROM product_master
WHERE company_id IS NOT NULL AND company_id != ''
ORDER BY company_id, brand, standard_product_name
"""

# Per-product data_status flag (Tier 1 / Tier 2 visual markers on v3):
#   tier1 — has registration evidence but at least one row missing registered_name
#   tier2 — all reg rows have registered_name, but at least one has
#           intended_use = unavailable_verified_* (no public indication)
#   (omit) — complete or no reg evidence
FLAG_QUERY = """
SELECT product_id, registered_name, intended_use
  FROM registration_evidence
 WHERE product_id IS NOT NULL AND product_id <> ''
"""

def clean(v) -> str:
    if v is None:
        return ""
    s = str(v).strip()
    return s


def compute_product_flags(conn) -> dict[str, str]:
    """Return {product_id: flag} for products that need a visual marker."""
    has_missing_name: set[str] = set()
    has_no_indication: set[str] = set()
    for pid, reg_name, intended in conn.execute(FLAG_QUERY):
        pid = clean(pid)
        if not pid:
            continue
        if not clean(reg_name):
            has_missing_name.add(pid)
        elif "unavailable_verified" in clean(intended).lower():
            has_no_indication.add(pid)
    out: dict[str, str] = {}
    for pid in has_missing_name:
        out[pid] = "tier1"
    for pid in has_no_indication:
        # tier1 takes precedence
        if pid not in out:
            out[pid] = "tier2"
    return out


def main() -> None:
    if not DB.exists():
        raise SystemExit(f"db not found: {DB}")
    conn = sqlite3.connect(str(DB))
    flags = compute_product_flags(conn)
    by_company: dict[str, list[dict]] = {}
    total = 0
    flag_counts = {"tier1": 0, "tier2": 0}
    for row in conn.execute(QUERY):
        (cid, pid, name, registered_name, brand, brand_role, cl1, cl2, tl1, tl2, mat, core,
         differentiator, tags) = row
        if not cid:
            continue
        rec = {
            "name":  clean(name) or clean(core) or clean(brand) or "未命名",
            "core":  clean(core),
            "brand": clean(brand),
            "brand_role": clean(brand_role),
            "l1": clean(cl1),
            "l2": clean(cl2),
            "tech": clean(tl1),
            "tech_l2": clean(tl2),
            "material": clean(mat),
            "differentiator": clean(differentiator),
            "tags": clean(tags),
        }
        # Only emit registered_name + flag when set, to keep JSON small.
        if clean(registered_name):
            rec["registered_name"] = clean(registered_name)
        flag = flags.get(clean(pid))
        if flag:
            rec["flag"] = flag
            flag_counts[flag] += 1
        by_company.setdefault(cid, []).append(rec)
        total += 1
    conn.close()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(by_company, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// auto-generated by scripts/_v3_build_products.py — do not hand-edit\n"
        f"// {total:,} products across {len(by_company):,} companies\n"
        f"window.V3_PRODUCTS_BY_COMPANY = {payload};\n",
        encoding="utf-8",
    )
    print(
        f"wrote {OUT.relative_to(ROOT)} · {total:,} products · "
        f"{len(by_company):,} companies · "
        f"flags tier1={flag_counts['tier1']} tier2={flag_counts['tier2']} · "
        f"{OUT.stat().st_size/1024:.1f} KB"
    )

if __name__ == "__main__":
    main()
