"""
Build a triage-ready JSON for the internal MDR/CE triage archive.

- Filters out mojibake rows (U+FFFD).
- Computes a priority score:
  - confidence tier (official_* > company_* > search_*)
  - company has existing FDA registration evidence (+ boost)
  - excerpt quality (length 80..800 = +1; >800 = -1; <80 = -1)
- Sorts by score desc, then company A-Z.
- Outputs web/v3/v3-mdr-ce-triage-data.js with window.V3_MDR_CE_DATA.
"""

from __future__ import annotations

import json
import sqlite3
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "global_aesthetics.db"
OUT = ROOT / "web" / "v3" / "v3-mdr-ce-triage-data.js"

CONF_SCORE = {
    "official_regulator_candidate": 4,
    "official_document_candidate": 3,
    "secondary_source_crosscheck": 2,
    "company_official_search_candidate": 1,
    "search_candidate_unverified": 0,
}


def main() -> None:
    con = sqlite3.connect(DB)
    cur = con.cursor()

    fda_companies = {
        r[0] for r in cur.execute(
            "select distinct company_id from registration_evidence where jurisdiction in ('US','USA')"
        )
    }

    candidates = []
    rows = cur.execute("""
        select evidence_id, plan_id, priority_rank, company_id, company,
               product_family_id, brand, product_family,
               source_key, source_name, title, url, published, captured_at,
               confidence, official_candidate, evidence_excerpt, crosscheck_status
        from mdr_ce_evidence_candidates
    """).fetchall()
    for r in rows:
        (evidence_id, plan_id, priority_rank, company_id, company,
         product_family_id, brand, product_family,
         source_key, source_name, title, url, published, captured_at,
         confidence, official_candidate, evidence_excerpt, crosscheck_status) = r

        excerpt = (evidence_excerpt or "")
        if "�" in excerpt:
            continue  # mojibake row

        score = CONF_SCORE.get(confidence or "", 0)
        if company_id in fda_companies:
            score += 2
        ex_len = len(excerpt)
        if 80 <= ex_len <= 800:
            score += 1
        elif ex_len > 800:
            score -= 1
        elif ex_len < 80:
            score -= 1
        # Title quality
        if title and 10 <= len(title) <= 140:
            score += 1

        candidates.append({
            "evidence_id": evidence_id,
            "company_id": company_id,
            "company": company,
            "brand": brand,
            "product_family": product_family,
            "source_key": source_key,
            "source_name": source_name,
            "title": (title or "")[:160],
            "url": url,
            "published": published,
            "confidence": confidence,
            "official_candidate": official_candidate,
            "score": score,
            "excerpt": excerpt[:600],
            "fda_company": company_id in fda_companies,
        })

    candidates.sort(key=lambda c: (-c["score"], c["company"] or ""))

    summary = {
        "total_after_filter": len(candidates),
        "filtered_mojibake": len(rows) - len(candidates),
        "by_source_key": dict(Counter(c["source_key"] for c in candidates).most_common()),
        "by_confidence": dict(Counter(c["confidence"] for c in candidates).most_common()),
        "by_top_company": dict(Counter(c["company"] for c in candidates).most_common(15)),
        "fda_company_overlap": sum(1 for c in candidates if c["fda_company"]),
    }

    out_text = (
        "// Auto-generated by scripts/_v3_build_mdr_ce_triage.py. Do not edit.\n"
        "window.V3_MDR_CE_DATA = "
        + json.dumps({"summary": summary, "candidates": candidates}, ensure_ascii=False, indent=1)
        + ";\n"
    )
    OUT.write_text(out_text, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  candidates after filter: {len(candidates)} (mojibake filtered: {summary['filtered_mojibake']})")
    print(f"  FDA-company overlap:     {summary['fda_company_overlap']}")
    print("  by confidence:", summary["by_confidence"])


if __name__ == "__main__":
    main()
